# package for generated api classes
apiPackage: browserup-mitmproxy-client
invokerPackage: BrowserUpProxyClient
licenseName: MIT
moduleName: BrowserUpProxyClient

projectDescription: "REST client for the BrowserUp Proxy"
projectName: browserup-mitmproxy-client
projectVersion: 1.0.0
