name: Publish Proxy Binary

# Tmp, will switch to on: release
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BINARY_PUBLISH_AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BINARY_PUBLISH_AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BINARY_PUBLISH_AWS_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'public'
